const ROUTES = {
  // NOTE Public Route
  HOME: "/",
  AUTH_ERROR_404_ALT: "/auth-error-404-alt",
  AUTH_ERROR_404_BASIC: "/auth-error-404-basic",
  AUTH_ERROR_500: "/auth-error-500",
  AUTH_ERROR_OFFLINE: "/auth-error-offline",
  AUTH_LOCKSCREEN_BASIC: "/auth-lockscreen-basic",
  AUTH_LOCKSCREEN_COVER: "/auth-lockscreen-cover",
  AUTH_LOGOUT_BASIC: "/auth-logout-basic",
  AUTH_LOGOUT_COVER: "/auth-logout-cover",
  AUTH_PASS_CHANGE_BASIC: "/auth-pass-change-basic",
  AUTH_PASS_CHANGE_COVER: "/auth-pass-change-cover",
  AUTH_PASS_REST_BASIC: "/auth-pass-reset-basic",
  AUTH_PASS_REST_COVER: "/auth-pass-reset-cover",
  AUTH_SIGNIN_BASIC: "/auth-signin-basic",
  AUTH_SIGNIN_COVER: "/auth-signin-cover",
  AUTH_SIGNUP_BASIC: "/auth-signup-basic",
  AUTH_SIGNUP_COVER: "/auth-signup-cover",
  AUTH_SUCCESS_MSG_BASIC: "/auth-success-msg-basic",
  AUTH_SUCCESS_MSG_COVER: "/auth-success-msg-cover",
  AUTH_TWOSTEP_BASIC: "/auth-twostep-basic",
  AUTH_TWOSTEP_COVER: "/auth-twostep-cover",

  JOB_LANDING: "/job-landing",
  LANDING: "/landing",
  NFT_LANDING: "/nft-landing",

  PAGES_COMMING_SOON: "/pages-coming-soon",
  PAGES_MAINTENANCE: "/pages-maintenance",

  // NOTE Protected Routes

  DASHBOARD_ECOMMERCE: "/dashboard",
  DASHBOARD_ANALYTICS: "/dashboard-analytics",
  DASHBOARD_BLOG: "/dashboard-blog",
  DASHBOARD_CRM: "/dashboard-crm",
  DASHBOARD_CRYPTO: "/dashboard-crypto",
  DASHBOARD_JOB: "/dashboard-job",
  DASHBOARD_NFT: "/dashboard-nft",
  DASHBOARD_PROJECTS: "/dashboard-projects",

  BLOG_ALL_POSTS: "/blog-all-posts",
  BLOG_CATEGORIES: "/blog-categories",

  IMAGE_LIBRARY_CONTROLS: "/image-library-controls",

  APPS_API_KEY: "/apps-api-key",
  APPS_CALENDAR_MONTH_GRID: "/apps-calendar-month-grid",
  APPS_MAIN_CALENDAR: "/apps-main-calendar",
  APPS_CHAT: "/apps-chat",
  APPS_CRM_COMPANIES: "/apps-crm-companies",
  APPS_CRM_CONTACTS: "/apps-crm-contacts",
  APPS_CRM_DEALS: "/apps-crm-deals",
  APPS_CRM_LEADS: "/apps-crm-leads",
  APPS_CRYPTO_BUY_SELL: "/apps-crypto-buy-sell",
  APPS_CRYPTO_ICO: "/apps-crypto-ico",
  APPS_CRYPTO_KYC: "/apps-crypto-kyc",
  APPS_CRYPTO_ORDERS: "/apps-crypto-orders",
  APPS_CRYPTO_TRANSACTIONS: "/apps-crypto-transactions",
  APPS_CRYPTO_WALLET: "/apps-crypto-wallet",
  APPS_ECOMMERCE_ADD_PRODUCT: "/apps-ecommerce-add-product",
  APPS_ECOMMERCE_CART: "/apps-ecommerce-cart",
  APPS_ECOMMERCE_CHECKOUT: "/apps-ecommerce-checkout",
  APPS_ECOMMERCE_CUSTOMERS: "/apps-ecommerce-customers",
  APPS_ECOMMERCE_ORDER_DETAILS: "/apps-ecommerce-order-details",
  APPS_ECOMMERCE_ORDERS: "/apps-ecommerce-orders",
  APPS_ECOMMERCE_PRODUCT_DETAILS: "/apps-ecommerce-product-details",
  APPS_ECOMMERCE_PRODUCTS: "/apps-ecommerce-products",
  APPS_ECOMMERCE_SELLER_DETAILS: "/apps-ecommerce-seller-details",
  APPS_ECOMMERCE_SELLERS: "/apps-ecommerce-sellers",
  APPS_EMAIL_BASIC: "/apps-email-basic",
  APPS_EMAIL_ECOMMERCE: "/apps-email-ecommerce",
  APPS_MAILBOX_EMAIL: "/apps-mailbox-email",
  APPS_FILE_MANAGER: "/apps-file-manager",
  APPS_INVOICES_CREATE: "/apps-invoices-create",
  APPS_INVOICES_DETAILS: "/apps-invoices-details",
  APPS_INVOICES_LIST: "/apps-invoices-list",
  APPS_JOB_CANDIDATE_GRID: "/apps-job-candidate-grid",
  APPS_JOB_CANDIDATE_LISTS: "/apps-job-candidate-lists",
  APPS_JOB_LISTS_DETAILS_VIEW: "/apps-job-lists-details-view",
  APPS_JOB_LISTS_GRID_VIEW: "/apps-job-lists-grid-view",
  APPS_JOB_LISTS_VIEW: "/apps-job-lists-view",
  APPS_JOB_APPLICATION: "/apps-job-application",
  APPS_JOB_CATEGORIES: "/apps-job-categories",
  APPS_JOB_COMPANIES_LISTS: "/apps-job-companies-lists",
  APPS_JOB_NEW: "/apps-job-new",
  APPS_JOB_STATISTICS: "/apps-job-statistics",
  APPS_NFT_AUCTION: "/apps-nft-auction",
  APPS_NFT_COLLECTIONS: "/apps-nft-collections",
  APPS_NFT_CREATE: "/apps-nft-create",
  APPS_NFT_CREATORS: "/apps-nft-creators",
  APPS_NFT_EXPLORE: "/apps-nft-explore",
  APPS_NFT_ITEM_DETAILS: "/apps-nft-item-details",
  APPS_NFT_MARKETPLACE: "/apps-nft-marketplace",
  APPS_NFT_RANKING: "/apps-nft-ranking",
  APPS_NFT_WALLET: "/apps-nft-wallet",
  APPS_PROJECTS_CREATE: "/apps-projects-create",
  APPS_PROJECTS_LIST: "/apps-projects-list",
  APPS_PROJECTS_OVERVIEW: "/apps-projects-overview",
  APPS_TICKETS_DETAILS: "/apps-tickets-details",
  APPS_TICKETS_LIST: "/apps-tickets-list",
  APPS_TASKS_DETAILS: "/apps-tasks-details",
  APPS_TASKS_KANBAN: "/apps-tasks-kanban",
  APPS_TASKS_LIST_VIEW: "/apps-tasks-list-view",
  APPS_TODO: "/apps-todo",

  PAGES_BLOG_GRID: "/pages-blog-grid",
  PAGES_BLOG_LIST: "/pages-blog-list",
  PAGES_BLOG_OVERVIEW: "/pages-blog-overview",
  PAGES_PROFILE: "/pages-profile",
  PAGES_USER_PROFILE_SETTINGS: "/pages-user-profile-settings",
  PAGES_FAQS: "/pages-faqs",
  PAGES_GALLERY: "/pages-gallery",
  PAGES_PRICING: "/pages-pricing",
  PAGES_PRIVACY_POLICY: "/pages-privacy-policy",
  PAGES_SEARCH_RESULTS: "/pages-search-results",
  PAGES_SITEMAP: "/pages-sitemap",
  PAGES_STARTER: "/pages-starter",
  PAGES_TEAM: "/pages-team",
  PAGES_TERMS_CONDITION: "/pages-terms-condition",
  PAGES_TIMELINE: "/pages-timeline",

  BASE_UI_ACCORDIONS: "/base-ui-accordions",
  BASE_UI_ALERTS: "/base-ui-alerts",
  BASE_UI_BADGES: "/base-ui-badges",
  BASE_UI_BUTTONS: "/base-ui-buttons",
  BASE_UI_CARDS: "/base-ui-cards",
  BASE_UI_CAROUSEL: "/base-ui-carousel",
  BASE_UI_COLORS: "/base-ui-colors",
  BASE_UI_DROPDOWNS: "/base-ui-dropdowns",
  BASE_UI_EMBED_VIDEO: "/base-ui-embed-video",
  BASE_UI_GENERAL: "/base-ui-general",
  BASE_UI_GRID: "/base-ui-grid",
  BASE_UI_IMAGES: "/base-ui-images",
  BASE_UI_LINKS: "/base-ui-links",
  BASE_UI_LISTS: "/base-ui-lists",
  BASE_UI_MEDIA: "/base-ui-media",
  BASE_UI_MODALS: "/base-ui-modals",
  BASE_UI_NOTIFICATIONS: "/base-ui-notifications",
  BASE_UI_OFFCANVAS: "/base-ui-offcanvas",
  BASE_UI_PLACEHOLDERS: "/base-ui-placeholders",
  BASE_UI_PROGRESS: "/base-ui-progress",
  BASE_UI_RIBBONS: "/base-ui-ribbons",
  BASE_UI_TABS: "/base-ui-tabs",
  BASE_UI_TYPOGRAPHY: "/base-ui-typography",
  BASE_UI_UTILITIES: "/base-ui-utilities",

  ADVANCE_UI_ANIMATION: "/advance-ui-animation",
  ADVANCE_UI_HIGHLIGHT: "/advance-ui-highlight",
  ADVANCE_UI_NESTABLE: "/advance-ui-nestable",
  ADVANCE_UI_RATINGS: "/advance-ui-ratings",
  ADVANCE_UI_SCROLLBAR: "/advance-ui-scrollbar",
  ADVANCE_UI_SWIPER: "/advance-ui-swiper",

  WIDGETS: "/widgets",

  FORMS_ADVANCED: "/forms-advanced",
  FORMS_CHECKBOXES_RADIOS: "/forms-checkboxes-radios",
  FORMS_EDITORS: "/forms-editors",
  FORMS_ELEMENTS: "/forms-elements",
  FORMS_FILE_UPLOADS: "/forms-file-uploads",
  FORMS_LAYOUTS: "/forms-layouts",
  FORMS_MASKS: "/forms-masks",
  FORMS_PICKERS: "/forms-pickers",
  FORMS_RANGE_SLIDERS: "/forms-range-sliders",
  FORMS_SELECT: "/forms-select",
  FORMS_SELECT2: "/forms-select2",
  FORMS_VALIDATION: "/forms-validation",
  FORMS_WIZARD: "/forms-wizard",

  TABLES_BASIC: "/tables-basic",
  TABLES_LISTJS: "/tables-listjs",
  TABLES_REACT: "/tables-react",

  CHARTS_APEX_AREA: "/charts-apex-area",
  CHARTS_APEX_BAR: "/charts-apex-bar",
  CHARTS_APEX_BOXPLOT: "/charts-apex-boxplot",
  CHARTS_APEX_BUBBLE: "/charts-apex-bubble",
  CHARTS_APEX_CANDLESTICK: "/charts-apex-candlestick",
  CHARTS_APEX_COLUMN: "/charts-apex-column",
  CHARTS_APEX_FUNNEL: "/charts-apex-funnel",
  CHARTS_APEX_HEATMAP: "/charts-apex-heatmap",
  CHARTS_APEX_LINE: "/charts-apex-line",
  CHARTS_APEX_MIXED: "/charts-apex-mixed",
  CHARTS_APEX_PIE: "/charts-apex-pie",
  CHARTS_APEX_POLAR: "/charts-apex-polar",
  CHARTS_APEX_RADAR: "/charts-apex-radar",
  CHARTS_APEX_RADIALBAR: "/charts-apex-radialbar",
  CHARTS_APEX_RANGE_AREA: "/charts-apex-range-area",
  CHARTS_APEX_SCATTER: "/charts-apex-scatter",
  CHARTS_APEX_SLOPE: "/charts-apex-slope",
  CHARTS_APEX_TIMELINE: "/charts-apex-timeline",
  CHARTS_APEX_TREEMAP: "/charts-apex-treemap",
  CHARTS_CHARTJS: "/charts-chartjs",
  CHARTS_ECHARTS: "/charts-echarts",

  ICONS_BOXICONS: "/icons-boxicons",
  ICONS_CRYPTO: "/icons-crypto",
  ICONS_FEATHER: "/icons-feather",
  ICONS_LINEAWESOME: "/icons-lineawesome",
  ICONS_MATERIALDESIGN: "/icons-materialdesign",
  ICONS_REMIX: "/icons-remix",

  PROFILE: "/profile",

  // NOTE Auth Routes

  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  AUTH_TWO_STEP: "/auth-twostep",
  AUTH_OTP_RESEND: "/auth-otp-resend",
  AUTH_PASS_CHANGE: "/auth-pass-change",

  // Dynamic Routes
  // AUTH_PASS_CHANGE: (token) => `/auth-pass-change/${token}`,
};

export default ROUTES;
